import type {
  User,
  Category,
  Equipment,
  Inspection,
  Report,
  QuoteRequest,
  Notification,
  ChecklistItem,
  Review,
} from './types'

export const CHECKLIST_TEMPLATE: ChecklistItem[] = [
  { section: 'MÉCANIQUE', label: 'Moteur', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Transmission', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Hydraulique', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Freinage', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Direction', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Pneus / chenilles', result: null, observation: '' },
  { section: 'ÉQUIPEMENT', label: 'Godet', result: null, observation: '' },
  { section: 'ÉQUIPEMENT', label: 'Bras', result: null, observation: '' },
  { section: 'ÉQUIPEMENT', label: 'Accessoires', result: null, observation: '' },
  { section: 'SÉCURITÉ', label: 'Dispositifs de sécurité', result: null, observation: '' },
  { section: 'SÉCURITÉ', label: 'Éclairage', result: null, observation: '' },
  { section: 'SÉCURITÉ', label: 'Signalisation', result: null, observation: '' },
  { section: 'ÉTAT GÉNÉRAL', label: 'Carrosserie', result: null, observation: '' },
  { section: 'ÉTAT GÉNÉRAL', label: 'Corrosion', result: null, observation: '' },
  { section: 'ÉTAT GÉNÉRAL', label: 'Usure', result: null, observation: '' },
]

export const users: User[] = [
  { id: 'u-admin', name: 'Kouadio Félix', role: 'ADMIN', company: 'VOLTA', email: 'admin@volta.ci', phone: '+225 07 00 00 01', city: 'Abidjan' },
  { id: 'u-sup-1', name: 'Boss Diarra', role: 'SUPPLIER', company: 'BTP CI SARL', email: 'contact@btpci.ci', phone: '+225 07 00 00 02', city: 'Abidjan' },
  { id: 'u-sup-2', name: 'Awa Koné', role: 'SUPPLIER', company: 'Afrique Matériel', email: 'contact@afriquemateriel.ci', phone: '+225 07 00 00 03', city: 'Yamoussoukro' },
  { id: 'u-tech-1', name: 'Yao Kouassi', role: 'TECHNICAL', company: 'Société Technique ABC', email: 'inspection@abc.ci', phone: '+225 07 00 00 04', city: 'Abidjan' },
  { id: 'u-client-1', name: 'Jean Konan', role: 'CLIENT', company: 'Entreprise BTP Konan', email: 'jean@konan.ci', phone: '+225 07 00 00 05', city: 'Abidjan' },
]

export const categories: Category[] = [
  { id: 'c-pelle', name: 'Pelles hydrauliques', icon: '🚜' },
  { id: 'c-chargeuse', name: 'Chargeuses', icon: '🏗️' },
  { id: 'c-benne', name: 'Bennes', icon: '🚚' },
  { id: 'c-bulldozer', name: 'Bulldozers', icon: '🛠️' },
  { id: 'c-compacteur', name: 'Compacteurs', icon: '⚙️' },
  { id: 'c-grue', name: 'Grues', icon: '🏙️' },
]

const photo = (seed: string) => `https://picsum.photos/seed/${seed}/640/420`

export const equipment: Equipment[] = [
  {
    id: 'eq-1',
    name: 'Caterpillar 320D2',
    categoryId: 'c-pelle',
    brand: 'Caterpillar',
    model: '320D2',
    year: 2016,
    hours: 4528,
    location: 'Abidjan, Côte d\'Ivoire',
    description: 'Pelle hydraulique fiable, puissante et économique en carburant. Idéale pour les travaux de terrassement, carrières et grands chantiers.',
    photos: [photo('cat320-1'), photo('cat320-2'), photo('cat320-3')],
    documents: [
      { name: 'Certificat CE', type: 'PDF' },
      { name: 'Rapport d\'inspection', type: 'PDF' },
    ],
    supplierId: 'u-sup-1',
    status: 'CATEGORISE',
    category: 'A',
    declaredCondition: 'Très bon état',
    createdAt: '2026-05-10',
    tier: 'GOLD',
    likes: 128,
  },
  {
    id: 'eq-2',
    name: 'Komatsu PC210LC-8',
    categoryId: 'c-pelle',
    brand: 'Komatsu',
    model: 'PC210LC-8',
    year: 2018,
    hours: 3900,
    location: 'Abidjan, Côte d\'Ivoire',
    description: 'Pelle hydraulique polyvalente, entretien à jour, prête pour chantier.',
    photos: [photo('komatsu-1'), photo('komatsu-2')],
    documents: [{ name: 'Certificat CE', type: 'PDF' }],
    supplierId: 'u-sup-2',
    status: 'CATEGORISE',
    category: 'B',
    declaredCondition: 'Bon état',
    createdAt: '2026-05-12',
    tier: 'SILVER',
    likes: 86,
  },
  {
    id: 'eq-3',
    name: 'Volvo A40G',
    categoryId: 'c-benne',
    brand: 'Volvo',
    model: 'A40G',
    year: 2019,
    hours: 2800,
    location: 'Abidjan, Côte d\'Ivoire',
    description: 'Tombereau articulé grande capacité pour transport de matériaux.',
    photos: [photo('volvo-1'), photo('volvo-2')],
    documents: [{ name: 'Documentation technique', type: 'PDF' }],
    supplierId: 'u-sup-1',
    status: 'DISPONIBLE',
    category: null,
    declaredCondition: 'Très bon état',
    createdAt: '2026-05-14',
    tier: 'GOLD',
    likes: 94,
  },
  {
    id: 'eq-4',
    name: 'Caterpillar D6T',
    categoryId: 'c-bulldozer',
    brand: 'Caterpillar',
    model: 'D6T',
    year: 2015,
    hours: 6100,
    location: 'Bouaké, Côte d\'Ivoire',
    description: 'Bulldozer robuste pour travaux de nivellement et défrichage.',
    photos: [photo('d6t-1')],
    documents: [{ name: 'Certificat CE', type: 'PDF' }],
    supplierId: 'u-sup-2',
    status: 'EN_INSPECTION',
    category: null,
    declaredCondition: 'Bon état',
    createdAt: '2026-05-15',
    tier: 'BASIC',
    likes: 31,
  },
  {
    id: 'eq-5',
    name: 'Hitachi ZX350LC-5',
    categoryId: 'c-pelle',
    brand: 'Hitachi',
    model: 'ZX350LC-5',
    year: 2017,
    hours: 5200,
    location: 'Abidjan, Côte d\'Ivoire',
    description: 'Pelle hydraulique lourde pour chantiers importants.',
    photos: [photo('hitachi-1'), photo('hitachi-2')],
    documents: [{ name: 'Facture', type: 'PDF' }],
    supplierId: 'u-sup-1',
    status: 'EN_INSPECTION',
    category: null,
    declaredCondition: 'Bon état',
    createdAt: '2026-08-10',
    tier: 'SILVER',
    likes: 57,
  },
  {
    id: 'eq-6',
    name: 'JCB 3CX',
    categoryId: 'c-chargeuse',
    brand: 'JCB',
    model: '3CX',
    year: 2020,
    hours: 1800,
    location: 'Abidjan, Côte d\'Ivoire',
    description: 'Tractopelle compacte très maniable.',
    photos: [photo('jcb-1')],
    documents: [],
    supplierId: 'u-sup-1',
    status: 'DISPONIBLE',
    category: null,
    declaredCondition: 'Très bon état',
    createdAt: '2026-08-11',
    tier: 'BASIC',
    likes: 22,
  },
]

export const quoteRequests: QuoteRequest[] = [
  {
    id: 'dv-001',
    reference: 'DV-2026-001',
    equipmentId: 'eq-1',
    supplierId: 'u-sup-1',
    clientName: 'Acme Corp',
    clientCompany: 'Acme Corporation',
    clientPhone: '+225 07 11 22 33',
    clientEmail: 'contact@acme.ci',
    duration: '5 jours',
    requestedDate: '2026-08-20',
    location: 'Abidjan Nord',
    message: 'Travaux de terrassement urgent',
    status: 'NOUVELLE',
    createdAt: '2026-08-12',
  },
  {
    id: 'dv-002',
    reference: 'DV-2026-002',
    equipmentId: 'eq-2',
    supplierId: 'u-sup-2',
    clientName: 'Construction Plus',
    clientCompany: 'Construction Plus SARL',
    clientPhone: '+225 07 44 55 66',
    clientEmail: 'info@constructionplus.ci',
    duration: '10 jours',
    requestedDate: '2026-08-25',
    location: 'Yamoussoukro',
    message: 'Projet de route',
    status: 'TRANSMISE',
    createdAt: '2026-08-11',
  },
]

export const inspections: Inspection[] = [
  {
    id: 'insp-1',
    quoteRequestId: 'dv-002',
    equipmentId: 'eq-4',
    technicalTeamId: 'u-tech-1',
    assignedAt: '2026-08-12',
    status: 'ASSIGNEE',
    checklist: CHECKLIST_TEMPLATE.map((c) => ({ ...c })),
    photos: [],
    anomalies: [],
  },
]

export const reports: Report[] = []

export const reviews: Review[] = [
  { id: 'rv-1', equipmentId: 'eq-1', author: 'Jean Konan', rating: 5, comment: 'Très bon état et conforme aux informations présentées. Livraison rapide sur chantier.', date: '2026-07-28', verified: true },
  { id: 'rv-2', equipmentId: 'eq-1', author: 'Mariam Touré', rating: 5, comment: 'Pelle puissante, aucun souci pendant 3 semaines de terrassement.', date: '2026-07-14', verified: true },
  { id: 'rv-3', equipmentId: 'eq-1', author: 'Ibrahim Sanogo', rating: 4, comment: 'Bon matériel, quelques heures au compteur mais très bien entretenu.', date: '2026-06-30', verified: false },
  { id: 'rv-4', equipmentId: 'eq-2', author: 'Aya Brou', rating: 5, comment: 'Machine impeccable, le fournisseur est très réactif.', date: '2026-07-20', verified: true },
  { id: 'rv-5', equipmentId: 'eq-2', author: 'Franck Ouattara', rating: 4, comment: 'Conforme au rapport d\'inspection VOLTA. Je recommande.', date: '2026-07-02', verified: true },
  { id: 'rv-6', equipmentId: 'eq-3', author: 'Sika Assi', rating: 5, comment: 'Tombereau très fiable pour le transport de latérite.', date: '2026-07-25', verified: true },
  { id: 'rv-7', equipmentId: 'eq-3', author: 'Moussa Camara', rating: 4, comment: 'Bonne capacité, consommation raisonnable.', date: '2026-06-18', verified: false },
  { id: 'rv-8', equipmentId: 'eq-4', author: 'Paul N\'Guessan', rating: 4, comment: 'Bulldozer robuste, parfait pour le défrichage.', date: '2026-07-10', verified: true },
  { id: 'rv-9', equipmentId: 'eq-5', author: 'Adjoua Kouamé', rating: 4, comment: 'Pelle lourde efficace sur notre carrière.', date: '2026-07-05', verified: true },
  { id: 'rv-10', equipmentId: 'eq-6', author: 'Serge Yao', rating: 5, comment: 'Tractopelle récente et très maniable en zone urbaine.', date: '2026-08-01', verified: true },
]

export const notifications: Notification[] = [
  { id: 'n-1', role: 'SUPPLIER', message: 'Nouvelle demande de devis DV-2026-001', date: '2026-08-12', read: false },
  { id: 'n-2', role: 'ADMIN', message: 'Demande de devis DV-2026-001 reçue', date: '2026-08-12', read: false },
  { id: 'n-3', role: 'TECHNICAL', message: 'Nouvelle mission d\'inspection INS-001 assignée', date: '2026-08-12', read: false },
]
