import type {
  User,
  Category,
  Equipment,
  Inspection,
  Report,
  RentalRequest,
  Notification,
  ChecklistItem,
} from './types'

export const CHECKLIST_TEMPLATE: ChecklistItem[] = [
  { section: 'MÉCANIQUE', label: 'Moteur', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Transmission', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Hydraulique', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Freinage', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Direction', result: null, observation: '' },
  { section: 'MÉCANIQUE', label: 'Pneus / chenilles', result: null, observation: '' },
  { section: 'ÉQUIPEMENT', label: 'Godet', result: null, observation: '' },
  { section: 'ÉQUIPEMENT', label: 'Bras', result: null, observation: '' },
  { section: 'ÉQUIPEMENT', label: 'Accessoires', result: null, observation: '' },
  { section: 'ÉQUIPEMENT', label: 'Équipements spécifiques', result: null, observation: '' },
  { section: 'SÉCURITÉ', label: 'Dispositifs de sécurité', result: null, observation: '' },
  { section: 'SÉCURITÉ', label: 'Éclairage', result: null, observation: '' },
  { section: 'SÉCURITÉ', label: 'Signalisation', result: null, observation: '' },
  { section: 'SÉCURITÉ', label: 'Équipements obligatoires', result: null, observation: '' },
  { section: 'ÉTAT GÉNÉRAL', label: 'Carrosserie', result: null, observation: '' },
  { section: 'ÉTAT GÉNÉRAL', label: 'Corrosion', result: null, observation: '' },
  { section: 'ÉTAT GÉNÉRAL', label: 'Usure', result: null, observation: '' },
  { section: 'ÉTAT GÉNÉRAL', label: 'Fonctionnement général', result: null, observation: '' },
]

export const users: User[] = [
  { id: 'u-admin', name: 'Kouadio Félix', role: 'ADMIN', company: 'VOLTA', email: 'admin@volta.ci', phone: '+225 07 00 00 01', city: 'Abidjan' },
  { id: 'u-sup-1', name: 'Boss Diarra', role: 'SUPPLIER', company: 'BTP CI SARL', email: 'contact@btpci.ci', phone: '+225 07 00 00 02', city: 'Abidjan' },
  { id: 'u-sup-2', name: 'Awa Koné', role: 'SUPPLIER', company: 'Afrique Matériel', email: 'contact@afriquemateriel.ci', phone: '+225 07 00 00 03', city: 'Yamoussoukro' },
  { id: 'u-tech-1', name: 'Yao Kouassi', role: 'TECHNICAL', company: 'Société Technique ABC', email: 'inspection@abc.ci', phone: '+225 07 00 00 04', city: 'Abidjan' },
  { id: 'u-client-1', name: 'Jean Konan', role: 'CLIENT', company: 'Entreprise BTP Konan', email: 'jean@konan.ci', phone: '+225 07 00 00 05', city: 'Abidjan' },
]

export const categories: Category[] = [
  { id: 'c-pelle', name: 'Pelles hydrauliques', icon: '🚜' },
  { id: 'c-chargeuse', name: 'Chargeuses', icon: '🏗️' },
  { id: 'c-benne', name: 'Bennes', icon: '🚚' },
  { id: 'c-bulldozer', name: 'Bulldozers', icon: '🛠️' },
  { id: 'c-compacteur', name: 'Compacteurs', icon: '⚙️' },
  { id: 'c-grue', name: 'Grues', icon: '🏙️' },
]

const photo = (seed: string) => `https://picsum.photos/seed/${seed}/640/420`

export const equipment: Equipment[] = [
  {
    id: 'eq-1',
    name: 'Caterpillar 320D2',
    categoryId: 'c-pelle',
    brand: 'Caterpillar',
    model: '320D2',
    year: 2016,
    hours: 4528,
    location: "Abidjan, Côte d'Ivoire",
    pricePerDay: 250000,
    available: true,
    withOperator: true,
    description:
      'Pelle hydraulique fiable, puissante et économique en carburant. Idéale pour les travaux de terrassement, carrières et grands chantiers.',
    photos: [photo('cat320-1'), photo('cat320-2'), photo('cat320-3')],
    documents: [
      { name: 'Certificat CE', type: 'PDF' },
      { name: "Facture d'achat", type: 'PDF' },
      { name: "Rapport d'inspection 2025", type: 'PDF' },
    ],
    supplierId: 'u-sup-1',
    status: 'PUBLISHED',
    level: 'GOLD',
    declaredCondition: 'Très bon état',
    createdAt: '2026-05-10',
  },
  {
    id: 'eq-2',
    name: 'Komatsu PC210LC-8',
    categoryId: 'c-pelle',
    brand: 'Komatsu',
    model: 'PC210LC-8',
    year: 2018,
    hours: 3900,
    location: "Abidjan, Côte d'Ivoire",
    pricePerDay: 220000,
    available: true,
    withOperator: false,
    description: 'Pelle hydraulique polyvalente, entretien à jour, prête pour chantier.',
    photos: [photo('komatsu-1'), photo('komatsu-2')],
    documents: [{ name: 'Certificat CE', type: 'PDF' }],
    supplierId: 'u-sup-2',
    status: 'PUBLISHED',
    level: 'SILVER',
    declaredCondition: 'Bon état',
    createdAt: '2026-05-12',
  },
  {
    id: 'eq-3',
    name: 'Volvo A40G',
    categoryId: 'c-benne',
    brand: 'Volvo',
    model: 'A40G',
    year: 2019,
    hours: 2800,
    location: "Abidjan, Côte d'Ivoire",
    pricePerDay: 350000,
    available: true,
    withOperator: true,
    description: 'Tombereau articulé grande capacité pour transport de matériaux.',
    photos: [photo('volvo-1'), photo('volvo-2')],
    documents: [{ name: "Manuel d'utilisation", type: 'PDF' }],
    supplierId: 'u-sup-1',
    status: 'PUBLISHED',
    level: 'GOLD',
    declaredCondition: 'Très bon état',
    createdAt: '2026-05-14',
  },
  {
    id: 'eq-4',
    name: 'Caterpillar D6T',
    categoryId: 'c-bulldozer',
    brand: 'Caterpillar',
    model: 'D6T',
    year: 2015,
    hours: 6100,
    location: "Bouaké, Côte d'Ivoire",
    pricePerDay: 180000,
    available: false,
    withOperator: true,
    description: 'Bulldozer robuste pour travaux de nivellement et défrichage.',
    photos: [photo('d6t-1')],
    documents: [{ name: 'Certificat CE', type: 'PDF' }],
    supplierId: 'u-sup-2',
    status: 'PUBLISHED',
    level: 'BASIC',
    declaredCondition: 'Bon état',
    createdAt: '2026-05-15',
  },
  {
    id: 'eq-5',
    name: 'Hitachi ZX350LC-5',
    categoryId: 'c-pelle',
    brand: 'Hitachi',
    model: 'ZX350LC-5',
    year: 2017,
    hours: 5200,
    location: "Abidjan, Côte d'Ivoire",
    pricePerDay: 270000,
    available: true,
    withOperator: false,
    description: 'Pelle hydraulique lourde, soumise pour vérification VOLTA.',
    photos: [photo('hitachi-1'), photo('hitachi-2')],
    documents: [{ name: "Facture d'achat", type: 'PDF' }],
    supplierId: 'u-sup-1',
    status: 'SUBMITTED',
    level: null,
    declaredCondition: 'Bon état',
    createdAt: '2026-08-10',
  },
  {
    id: 'eq-6',
    name: 'JCB 3CX',
    categoryId: 'c-chargeuse',
    brand: 'JCB',
    model: '3CX',
    year: 2020,
    hours: 1800,
    location: "Abidjan, Côte d'Ivoire",
    pricePerDay: 150000,
    available: true,
    withOperator: false,
    description: 'Tractopelle compacte en cours de vérification.',
    photos: [photo('jcb-1')],
    documents: [],
    supplierId: 'u-sup-1',
    status: 'PENDING_INSPECTION',
    level: null,
    declaredCondition: 'Très bon état',
    createdAt: '2026-08-11',
  },
  {
    id: 'eq-7',
    name: 'Liebherr LTM 1050',
    categoryId: 'c-grue',
    brand: 'Liebherr',
    model: 'LTM 1050',
    year: 2014,
    hours: 8000,
    location: "Yamoussoukro, Côte d'Ivoire",
    pricePerDay: 500000,
    available: true,
    withOperator: true,
    description: 'Grue mobile 50 tonnes. Brouillon en cours de complétion.',
    photos: [photo('liebherr-1')],
    documents: [],
    supplierId: 'u-sup-1',
    status: 'DRAFT',
    level: null,
    declaredCondition: 'État moyen',
    createdAt: '2026-08-13',
  },
  {
    id: 'eq-8',
    name: 'Bomag BW213',
    categoryId: 'c-compacteur',
    brand: 'Bomag',
    model: 'BW213',
    year: 2016,
    hours: 4100,
    location: "Bouaké, Côte d'Ivoire",
    pricePerDay: 120000,
    available: true,
    withOperator: false,
    description: 'Compacteur monocylindre, rapport transmis, en attente de décision.',
    photos: [photo('bomag-1')],
    documents: [{ name: 'Certificat CE', type: 'PDF' }],
    supplierId: 'u-sup-2',
    status: 'PENDING_ADMIN_REVIEW',
    level: null,
    declaredCondition: 'Bon état',
    createdAt: '2026-08-08',
  },
]

export const inspections: Inspection[] = [
  {
    id: 'insp-1',
    equipmentId: 'eq-6',
    technicalTeamId: 'u-tech-1',
    assignedAt: '2026-08-12',
    status: 'ASSIGNED',
    checklist: CHECKLIST_TEMPLATE.map((c) => ({ ...c })),
    photos: [],
    anomalies: [],
  },
  {
    id: 'insp-2',
    equipmentId: 'eq-8',
    technicalTeamId: 'u-tech-1',
    assignedAt: '2026-08-09',
    status: 'DONE',
    checklist: CHECKLIST_TEMPLATE.map((c) => ({ ...c, result: 'CONFORME' as const })),
    photos: [photo('insp-bomag')],
    anomalies: [],
  },
]

export const reports: Report[] = [
  {
    id: 'rep-1',
    inspectionId: 'insp-2',
    equipmentId: 'eq-8',
    submittedAt: '2026-08-10',
    summary: 'Équipement globalement conforme. Aucune anomalie majeure détectée.',
    checklist: CHECKLIST_TEMPLATE.map((c) => ({ ...c, result: 'CONFORME' as const })),
  },
]

export const rentalRequests: RentalRequest[] = [
  {
    id: 'req-1',
    reference: 'VOL-2026-00123',
    equipmentId: 'eq-1',
    supplierId: 'u-sup-1',
    startDate: '2026-08-20',
    endDate: '2026-09-20',
    location: 'Chantier Abidjan Nord',
    withOperator: true,
    transport: true,
    comment: 'Travaux de terrassement, besoin urgent.',
    clientName: 'Jean Konan',
    clientPhone: '+225 07 00 00 05',
    clientEmail: 'jean@konan.ci',
    status: 'PENDING',
    createdAt: '2026-08-14',
  },
]

export const notifications: Notification[] = [
  { id: 'n-1', role: 'ADMIN', message: 'Hitachi ZX350LC-5 soumis par BTP CI SARL', date: '2026-08-10', read: false },
  { id: 'n-2', role: 'SUPPLIER', message: 'Votre équipement JCB 3CX est en attente d\'inspection', date: '2026-08-12', read: false },
  { id: 'n-3', role: 'TECHNICAL', message: 'Nouvelle mission assignée : JCB 3CX', date: '2026-08-12', read: false },
]
